version: '3.8'

services:

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pokemon

  pokemon.js:
    pull_policy: always
    image: ghcr.io/larvepoire/node-api:main
    container_name: pokemon
    restart: always
    ports:
      - 0.0.0.0:20000:8080
    environment:
      - MYSQL_NAME=pokemon
      - MYSQL_ID=root
      - MYSQL_PASS=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - PORT=8080